name: Continuous Integration

on: [push]

jobs:
  build:

    runs-on: ubuntu-latest
    strategy:
      matrix:
        node_version: [20]

    steps:
    - uses: actions/checkout@v4

    - uses: pnpm/action-setup@v4
      with:
        version: 9.0.6

    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v4
      with:
        node-version: ${{ matrix.node-version }}
        # cache: "pnpm"

    - name: Setup Clojure
      uses: DeLaGuardo/setup-clojure@12.6
      with:
        cli: '1.11.3.1463'

    - name: Clojure dependency cache
      uses: actions/cache@v4
      with:
        path: |
          ~/.m2
          .cpcache
        key: cljdeps-${{ runner.os }}-${{ hashFiles('deps.edn') }}
        restore-keys: |
            cljdeps-${{ runner.os }}-

    - name: Verify Lint
      run: pnpm lint --config '{:output {:pattern "::{{level}} file={{filename}},line={{row}},col={{col}}::{{message}}"}}'

    - name: Verify Tests
      run: pnpm test


